version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=tcc_java
      - POSTGRES_PASSWORD=tcc_java
      - POSTGRES_DB=tcc_java
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data/base.sql:/docker-entrypoint-initdb.d/base.sql
      - ./data/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    networks:
      - app
    ports:
      - "5432:5432"
    restart: always

  app:
    container_name: catgram
    build:
      context: .
      dockerfile: Dockerfile
    image: catgram
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tcc_java
      - SPRING_DATASOURCE_USER=tcc_java
      - SPRING_DATASOURCE_PASSWORD=tcc_java
    ports:
      - "8081:8081"
    networks:
      - app
    depends_on:
      - postgres

volumes:
  postgres-data:

networks:
  app:
